---
- name: Install connman
  become: True
  apt:
    name:
      - connman

- name: Install wpa_supplicant
  become: True
  apt:
    name:
      - wpasupplicant
  when: connman_use_wpa_supplicant

- name: Create systemd service directory
  become: True
  file:
    path: /etc/systemd/system/connman.service.d
    state: directory

- name: Disable connman dns proxy
  become: True
  copy:
    src: override.conf
    dest: /etc/systemd/system/connman.service.d/override.conf
  notify:
    - restart connman
    - restart wpa_supplicant

- name: Configure connman
  become: True
  template:
    src: main.conf.j2
    dest: /etc/connman/main.conf
  notify:
    - restart connman
    - restart wpa_supplicant

- name: Link /run/connman/resolv.conf to /etc/
  become: True
  file:
    src: /run/connman/resolv.conf
    dest: /etc/resolv.conf
    force: yes
    state: link

- name: Configure networks
  become: True
  template:
    src: service.j2
    dest: "/var/lib/connman/{{ item.name }}.config"
    mode: 0600
  with_items: "{{ connman_networks }}"
  notify:
    - restart connman
    - restart wpa_supplicant
